import { createFileRoute } from "@tanstack/react-router";
import { SiteFooter } from "@/components/site/SiteFooter";
import { SiteNav } from "@/components/site/SiteNav";

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [{ title: "Terms of Service — HomeAfford" }, { name: "description", content: "HomeAfford terms of service." }] }),
  component: TermsPage,
});

const sections = [
  ["About HomeAfford", "HomeAfford is a planning and decision-support tool. It does not provide financial, investment, or loan advice."],
  ["Disclaimer", "All plans and suggestions generated by HomeAfford are for informational purposes only. Please consult a qualified financial advisor before making any financial decisions."],
  ["Subscription", "Pro subscriptions are billed monthly or annually via Razorpay. You can cancel anytime from account settings."],
  ["Limitation of liability", "HomeAfford is not liable for any financial decisions made based on the plans generated by this tool."],
  ["Contact", "[placeholder email]"],
];

function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <SiteNav />
      <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-12 sm:px-6 sm:py-16">
        <h1 className="text-3xl font-extrabold tracking-tight text-foreground sm:text-4xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: April 2026</p>
        <div className="mt-10 space-y-8">
          {sections.map(([heading, body], index) => (
            <section key={heading}>
              <h2 className="text-lg font-bold text-foreground">{index + 1}. {heading}</h2>
              <p className="mt-2 leading-7 text-muted-foreground">{body}</p>
            </section>
          ))}
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}