/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanNewRouteImport } from './routes/plan.new'
import { Route as ApiGeneratePlanSuggestionsRouteImport } from './routes/api.generate-plan-suggestions'
import { Route as ApiExtractBuilderPaymentPlanRouteImport } from './routes/api.extract-builder-payment-plan'
import { Route as ApiCreateRazorpaySubscriptionRouteImport } from './routes/api.create-razorpay-subscription'
import { Route as ApiConfirmRazorpaySubscriptionRouteImport } from './routes/api.confirm-razorpay-subscription'
import { Route as ApiAnalyzeBankStatementRouteImport } from './routes/api.analyze-bank-statement'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanNewRoute = PlanNewRouteImport.update({
  id: '/plan/new',
  path: '/plan/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePlanSuggestionsRoute =
  ApiGeneratePlanSuggestionsRouteImport.update({
    id: '/api/generate-plan-suggestions',
    path: '/api/generate-plan-suggestions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExtractBuilderPaymentPlanRoute =
  ApiExtractBuilderPaymentPlanRouteImport.update({
    id: '/api/extract-builder-payment-plan',
    path: '/api/extract-builder-payment-plan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCreateRazorpaySubscriptionRoute =
  ApiCreateRazorpaySubscriptionRouteImport.update({
    id: '/api/create-razorpay-subscription',
    path: '/api/create-razorpay-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConfirmRazorpaySubscriptionRoute =
  ApiConfirmRazorpaySubscriptionRouteImport.update({
    id: '/api/confirm-razorpay-subscription',
    path: '/api/confirm-razorpay-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyzeBankStatementRoute = ApiAnalyzeBankStatementRouteImport.update({
  id: '/api/analyze-bank-statement',
  path: '/api/analyze-bank-statement',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/analyze-bank-statement': typeof ApiAnalyzeBankStatementRoute
  '/api/confirm-razorpay-subscription': typeof ApiConfirmRazorpaySubscriptionRoute
  '/api/create-razorpay-subscription': typeof ApiCreateRazorpaySubscriptionRoute
  '/api/extract-builder-payment-plan': typeof ApiExtractBuilderPaymentPlanRoute
  '/api/generate-plan-suggestions': typeof ApiGeneratePlanSuggestionsRoute
  '/plan/new': typeof PlanNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/analyze-bank-statement': typeof ApiAnalyzeBankStatementRoute
  '/api/confirm-razorpay-subscription': typeof ApiConfirmRazorpaySubscriptionRoute
  '/api/create-razorpay-subscription': typeof ApiCreateRazorpaySubscriptionRoute
  '/api/extract-builder-payment-plan': typeof ApiExtractBuilderPaymentPlanRoute
  '/api/generate-plan-suggestions': typeof ApiGeneratePlanSuggestionsRoute
  '/plan/new': typeof PlanNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/analyze-bank-statement': typeof ApiAnalyzeBankStatementRoute
  '/api/confirm-razorpay-subscription': typeof ApiConfirmRazorpaySubscriptionRoute
  '/api/create-razorpay-subscription': typeof ApiCreateRazorpaySubscriptionRoute
  '/api/extract-builder-payment-plan': typeof ApiExtractBuilderPaymentPlanRoute
  '/api/generate-plan-suggestions': typeof ApiGeneratePlanSuggestionsRoute
  '/plan/new': typeof PlanNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/analyze-bank-statement'
    | '/api/confirm-razorpay-subscription'
    | '/api/create-razorpay-subscription'
    | '/api/extract-builder-payment-plan'
    | '/api/generate-plan-suggestions'
    | '/plan/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/analyze-bank-statement'
    | '/api/confirm-razorpay-subscription'
    | '/api/create-razorpay-subscription'
    | '/api/extract-builder-payment-plan'
    | '/api/generate-plan-suggestions'
    | '/plan/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/analyze-bank-statement'
    | '/api/confirm-razorpay-subscription'
    | '/api/create-razorpay-subscription'
    | '/api/extract-builder-payment-plan'
    | '/api/generate-plan-suggestions'
    | '/plan/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ApiAnalyzeBankStatementRoute: typeof ApiAnalyzeBankStatementRoute
  ApiConfirmRazorpaySubscriptionRoute: typeof ApiConfirmRazorpaySubscriptionRoute
  ApiCreateRazorpaySubscriptionRoute: typeof ApiCreateRazorpaySubscriptionRoute
  ApiExtractBuilderPaymentPlanRoute: typeof ApiExtractBuilderPaymentPlanRoute
  ApiGeneratePlanSuggestionsRoute: typeof ApiGeneratePlanSuggestionsRoute
  PlanNewRoute: typeof PlanNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/new': {
      id: '/plan/new'
      path: '/plan/new'
      fullPath: '/plan/new'
      preLoaderRoute: typeof PlanNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-plan-suggestions': {
      id: '/api/generate-plan-suggestions'
      path: '/api/generate-plan-suggestions'
      fullPath: '/api/generate-plan-suggestions'
      preLoaderRoute: typeof ApiGeneratePlanSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-builder-payment-plan': {
      id: '/api/extract-builder-payment-plan'
      path: '/api/extract-builder-payment-plan'
      fullPath: '/api/extract-builder-payment-plan'
      preLoaderRoute: typeof ApiExtractBuilderPaymentPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-razorpay-subscription': {
      id: '/api/create-razorpay-subscription'
      path: '/api/create-razorpay-subscription'
      fullPath: '/api/create-razorpay-subscription'
      preLoaderRoute: typeof ApiCreateRazorpaySubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/confirm-razorpay-subscription': {
      id: '/api/confirm-razorpay-subscription'
      path: '/api/confirm-razorpay-subscription'
      fullPath: '/api/confirm-razorpay-subscription'
      preLoaderRoute: typeof ApiConfirmRazorpaySubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-bank-statement': {
      id: '/api/analyze-bank-statement'
      path: '/api/analyze-bank-statement'
      fullPath: '/api/analyze-bank-statement'
      preLoaderRoute: typeof ApiAnalyzeBankStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ApiAnalyzeBankStatementRoute: ApiAnalyzeBankStatementRoute,
  ApiConfirmRazorpaySubscriptionRoute: ApiConfirmRazorpaySubscriptionRoute,
  ApiCreateRazorpaySubscriptionRoute: ApiCreateRazorpaySubscriptionRoute,
  ApiExtractBuilderPaymentPlanRoute: ApiExtractBuilderPaymentPlanRoute,
  ApiGeneratePlanSuggestionsRoute: ApiGeneratePlanSuggestionsRoute,
  PlanNewRoute: PlanNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
